# Generated by Django 4.1.5 on 2023-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("football", "football"),
                            ("cricket", "cricket"),
                            ("hockey", "hockey"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
