# Generated by Django 4.1.5 on 2023-02-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("phone_no", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("football", "football"),
                            ("cricket", "cricket"),
                            ("hockey", "hockey"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("4PM", "4PM"),
                            ("5PM", "5PM"),
                            ("6PM", "6PM"),
                            ("7PM", "7PM"),
                            ("8PM", "8PM"),
                            ("9PM", "9PM"),
                            ("10PM", "10PM"),
                            ("11PM", "11PM"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playspots_app.user",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playspots_app.venue",
                    ),
                ),
            ],
        ),
    ]
