# Generated by Django 4.1.5 on 2023-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playspots_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking", name="count", field=models.PositiveIntegerField(),
        ),
    ]
