# Generated by Django 4.1.5 on 2023-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playspots_app", "0002_alter_booking_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="count",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
