# Generated by Django 4.1.5 on 2023-02-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playspots_app", "0004_alter_booking_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="count",),
    ]
